" Format
filetype indent plugin on
set encoding=utf-8
syntax enable

" Display
set number
set wildmenu

" Behavior
set autoread
set lazyredraw
set mouse=a
set updatetime=200
set visualbell

" Search
set nohlsearch
set incsearch
set ignorecase
set smartcase

" Indentation
set autoindent
set backspace=indent,eol,start
set expandtab
set shiftwidth=2
set softtabstop=2

" Fuzzy finder
set rtp+=~/.fzf

" Plugin
let g:netrw_dirhistmax = 0
call plug#begin()
Plug 'airblade/vim-gitgutter'
Plug 'ajh17/vimcompletesme'
Plug 'junegunn/fzf.vim'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'w0rp/ale'
call plug#end()

" Style
let g:airline_theme='monochrome'

" Lint
let g:ale_fix_on_save = 1
let g:ale_fixers = {
\   'typescript': ['prettier'],
\   'javascript': ['prettier'],
\   'css': ['prettier'],
\   'scss': ['prettier'],
\   'python': ['autopep8'],
\}
let g:ale_lint_on_enter = 0
